// This file is auto-generated by @hey-api/openapi-ts

export type BodyDeployProgramDeployPost = {
    file: Blob | File;
    environment?: string;
};

export type BodyUploadFileUploadPost = {
    file: Blob | File;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileUploadPostData = {
    body: BodyUploadFileUploadPost;
    path?: never;
    query?: never;
    url: '/upload';
};

export type UploadFileUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileUploadPostError = UploadFileUploadPostErrors[keyof UploadFileUploadPostErrors];

export type UploadFileUploadPostResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UploadFileUploadPostResponse = UploadFileUploadPostResponses[keyof UploadFileUploadPostResponses];

export type DeployProgramDeployPostData = {
    body: BodyDeployProgramDeployPost;
    path?: never;
    query?: never;
    url: '/deploy';
};

export type DeployProgramDeployPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeployProgramDeployPostError = DeployProgramDeployPostErrors[keyof DeployProgramDeployPostErrors];

export type DeployProgramDeployPostResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeployProgramDeployPostResponse = DeployProgramDeployPostResponses[keyof DeployProgramDeployPostResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};